#!/bin/bash
set -uo pipefail

# ----- HELPER FUNCTIONS -----

check_dependencies_fun() {
    if ! command -v {podman,docker,lilipod} &>/dev/null; then
        printf "A container engine must be installed.\n"; exit 1
    fi
    if ! command -v distrobox &>/dev/null; then
        printf "Distrobox must be installed.\nhttps://distrobox.it/#installation\n"; exit 1
    fi
}

file_extraction_fun() {
    local FILEPATH

    FP_TEMP_DIR="$(mktemp -d "$HOME/.flashpoint/flashpoint.XXXXXX")"
    read -e -p "Enter the location of the Flashpoint .7z file: " FILEPATH; FILEPATH="${FILEPATH/#\~/$HOME}"

    if [ ! -f "$FILEPATH" ]; then
        printf "File does not exist\n"; rm -rf "$FP_TEMP_DIR"; exit 2
    fi
    if [[ "$FILEPATH" != *.7z ]]; then
        printf "The file must be a .7z archive\n"; rm -rf "$FP_TEMP_DIR"; exit 2
    fi

    if distrobox-enter Flashpoint -T -- bash -c '7za l "$1" | grep -q "version.txt"' bash "$FILEPATH" &>/dev/null; then
        printf "Extracting the zip file..\n"
        if ! distrobox-enter Flashpoint -T -- bash -c '7za x "$1" -o"$2"' bash "$FILEPATH" "$FP_TEMP_DIR" &>/dev/null; then
            printf "Extraction failed!\n"; distrobox-stop Flashpoint -Y &>/dev/null; rm -rf "$FP_TEMP_DIR"; exit 1
        fi
    else
        printf "The provided .7z archive wasn't Flashpoint.\n"; distrobox-stop Flashpoint -Y &>/dev/null; rm -rf "$FP_TEMP_DIR"; exit 2
    fi

    distrobox-stop Flashpoint -Y &>/dev/null
    rm -rf "$FP_TEMP_DIR/Libraries"; rm -rf "$FP_TEMP_DIR/FPSoftware/Wine"; mkdir -p "$FP_TEMP_DIR/FPSoftware/Wine"
}

check_install_fun() {
    if ! grep -q "Flashpoint" "$HOME/.flashpoint/fp-dt/version.txt" 2>/dev/null; then
        return 1
    fi
}

check_distrobox_fun() {
    if ! distrobox list | grep -q '\<Flashpoint\>' 2>/dev/null; then
        printf "Flashpoint is installed but the Distrobox container is missing?\nRunning --restore-distrobox is recommended.\n"; exit 2
    fi
}

help_list_fun() {
    cat <<EOF
Usage:
--help                 |  Brings up the manager options.
--install-flashpoint   |  Installs Flashpoint and the Distrobox container.
--update-flashpoint    |  Updates Flashpoint.
--reinstall-flashpoint |  Re-installs Flashpoint and the Distrobox container.
--delete-flashpoint    |  Deletes Flashpoint the Distrobox container.
--enable-wine-wayland  |  Enables Wine native Wayland. (Disabled by default)
--disable-wine-wayland |  Disables Wine native Wayland. (Disabled by default)
--enable-audio-fix     |  Enables ALSA audio backend for Wine this can fix issue with audio. (Disabled by default)
--disable-audio-fix    |  Disables the ALSA audio backend in favor of PulseAudio. (Disabled by default)
--restore-distrobox    |  Restores Distrobox container if it was deleted. (User data will be safe)
EOF
}

# ----- INSTALLATION FUNCTIONS -----

create_distrobox_fun() {
    if distrobox list | grep -q '\<Flashpoint\>' 2>/dev/null; then
        printf "The Distrobox container already exists. (Did you already have a Distrobox contained named 'Flashpoint'?)\nInstallation will attempt to continue.\n"; return 0
    fi
    printf "Distrobox will install a Fedora 40 image with all the dependencies for Flashpoint. (This will take a while)\n"
    if ! distrobox-create \
            --no-entry \
            --image fedora:40 \
            --home "$HOME/.flashpoint/" \
            --name Flashpoint \
            --nvidia \
            -Y &>/dev/null; then
        printf "Failed to create the Distrobox container.\n"; exit 1
    fi
    if ! distrobox-enter Flashpoint -T -- bash -c 'sudo dnf install xorg-x11-server-Xwayland gtk3 nss pipewire-pulseaudio php p7zip wine libXcomposite.i686 pulseaudio-libs.i686 gtk2 libXt -y' &>/dev/null; then
        printf "Failed to install dependencies inside the Distrobox container.\n"; exit 1
    fi
    distrobox-stop Flashpoint -Y &>/dev/null
}

finish_install_fun() {
    mv "$FP_TEMP_DIR" "$HOME/.flashpoint/fp-dt"
    distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wineboot' &>/dev/null
    distrobox-stop Flashpoint -Y &>/dev/null

    mkdir -p "$HOME/.local/bin"
    cat > "$HOME/.local/bin/flashpointwrapper.sh" <<EOF
#!/bin/bash
trap "distrobox-stop Flashpoint --yes" EXIT
distrobox-enter Flashpoint -T -- bash -c '/usr/bin/env -S WINEPREFIX="$HOME/.flashpoint/fp-dt/FPSoftware/Wine" "$HOME/.flashpoint/fp-dt/Launcher/flashpoint-launcher" --js-flags=--lite_mode --ozone-platform-hint=auto'
EOF
    cat > "$HOME/.local/share/applications/flashpoint-archive.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Flashpoint Archive
Comment=An archive for games and animations from the web.
Icon=$HOME/.flashpoint/fp-dt/Launcher/icon.svg
StartupWMClass=flashpoint-launcher
Exec=$HOME/.local/bin/flashpointwrapper.sh
Path=$HOME/.flashpoint/fp-dt/Launcher
Terminal=false
Categories=Archiving;Game;
SingleMainWindow=true
EOF
    chmod +x "$HOME/.local/bin/flashpointwrapper.sh"; update-desktop-database ~/.local/share/applications; printf "Flashpoint has been installed.\n"; exit 0
}

# ----- DELETION FUNCTIONS -----

delete_distrobox_fun() {
    distrobox-rm Flashpoint -f -Y &>/dev/null
}

delete_fp_fun() {
    rm -rf "$HOME/.flashpoint"
    rm -f "$HOME/.local/bin/flashpointwrapper.sh"
    rm -f "$HOME/.local/share/applications/flashpoint-archive.desktop"
}

# ---- MANAGEMENT FUNCTIONS -----

# This function updates (or downgrades) Flashpoint and tries its best to preserve data.
# The update proccess kinda sucks because it is complicated, but whatever it works and IMO it is the best way of updating.
# The update works by taking a new .7z Flashpoint file and cross checking the "version.txt" file inside it with the currently installed one.
# This allows for downgrades also but this isn't made for that.
# If an update is needed then the simple way of explaining it is the user data from their current install is copied to a temporary directory.
# Then the users whole Flashpoint install gets deleted and replaced with the new version that was extracted.
# After that the user data gets put back where it needs to be and some clean ups happen thats it.
update_fp_fun() {
    local YN USERDATA

    if [ "$(< "$FP_TEMP_DIR/version.txt")" = "$(< "$HOME/.flashpoint/fp-dt/version.txt")" ]; then
        printf "Flashpoint is already up-to-date.\n"; rm -rf "$FP_TEMP_DIR"; exit 0
    fi

    printf "Flashpoint is outdated! Would you like to update?\n"
    read -rp "[Y/n] " YN; YN="${YN:-Y}"
    if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
        printf "Starting update..\n"
    elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
        printf "Canceling update.\n"; rm -rf "$FP_TEMP_DIR"; exit 0
    else
        printf "Unknown option, exiting..\n"; rm -rf "$FP_TEMP_DIR"; exit 2
    fi

    # Save user data.
    USERDATA="$(mktemp -d "$HOME/.flashpoint/userdata.XXXXXX")"
    cp "$HOME/.flashpoint/fp-dt/preferences.json" "$USERDATA"
    cp "$HOME/.flashpoint/fp-dt/Data/Playlists/Favorites.json" "$USERDATA"
    cp "$HOME/.flashpoint/fp-dt/Data/flashpoint.sqlite" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/Data/Games" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/Legacy/htdocs" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/FPSoftware/Wine" "$USERDATA"

    # Remove fp-dt and replace with the new version.
    rm -rf "$HOME/.flashpoint/fp-dt/"; mv "$FP_TEMP_DIR" "$HOME/.flashpoint/fp-dt"

    # Remove conflicting data.
    rm -f "$HOME/.flashpoint/fp-dt/preferences.json"
    rm -f "$HOME/.flashpoint/fp-dt/Data/Playlists/Favorites.json"
    rm -f "$HOME/.flashpoint/fp-dt/Data/flashpoint.sqlite"
    rm -rf "$HOME/.flashpoint/fp-dt/Data/Games"
    rm -rf "$HOME/.flashpoint/fp-dt/Legacy/htdocs"

    # Restore user data.
    cp "$USERDATA/preferences.json" "$HOME/.flashpoint/fp-dt"
    cp "$USERDATA/Favorites.json" "$HOME/.flashpoint/fp-dt/Data/Playlists/"
    cp "$USERDATA/flashpoint.sqlite" "$HOME/.flashpoint/fp-dt/Data/"
    cp -r "$USERDATA/Games" "$HOME/.flashpoint/fp-dt/Data/"
    cp -r "$USERDATA/htdocs" "$HOME/.flashpoint/fp-dt/Legacy/"
    cp -r "$USERDATA/Wine" "$HOME/.flashpoint/fp-dt/FPSoftware/"

    # Remove extra user data directory.
    rm -rf "$USERDATA"; printf "Flashpoint has been updated.\n"
}

ad_fx_on_fun() {
    local YN

    if [ "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" = '"Audio"="alsa"' ]; then
        printf "Audio fix is already enabled.\n"; exit 2
    fi

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    if ! distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Audio /d alsa /f' &>/dev/null; then
        printf "Failed to enabled audio fix.\n"; exit 1
    fi
    distrobox-stop Flashpoint -Y &>/dev/null; printf "Audio fix enabled.\n"; exit 0
}

ad_fx_off_fun() {
    local YN

    if [ "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" = '"Audio"="pulse"' ] || [ -z "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" ]; then
        printf "Audio fix is already disabled\n"; exit 2
    fi

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    if ! distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Audio /d pulse /f' &>/dev/null; then
        printf "Failed to disable audio fix.\n"; exit 1
    fi
    distrobox-stop Flashpoint -Y &>/dev/null; printf "Audio fix disabled.\n"; exit 0
}

win_wy_off_fun() {
    local YN

    if [ "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" = '"Graphics"="x11,wayland"' ] || [ -z "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" ]; then
        printf "X11 is already in use.\n"; exit 2
    fi

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    if ! distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Graphics /d x11,wayland /f' &>/dev/null; then
        printf "Failed to disable WINE Wayland.\n"; exit 1
    fi
    distrobox-stop Flashpoint -Y &>/dev/null; printf "Wine Wayland disabled.\n"; exit 0
}

win_wy_on_fun() {
    local YN

    if [ "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg" 2>/dev/null)" = '"Graphics"="wayland,x11"' ]; then
        printf "Wine native Wayland already in use.\n"; exit 2
    fi

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    if ! distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Graphics /d wayland,x11 /f' &>/dev/null; then
        printf "Failed to enable WINE Wayland.\n"; exit 1
    fi
    distrobox-stop Flashpoint -Y &>/dev/null; printf "Wine Wayland enabled.\n"; exit 0
}

# ----- FUN -----

easter_egg_fun() {
    printf "You found the easter egg! :)\nThis is my favorite game on Flashpoint.\nhttps://flashpointproject.github.io/flashpoint-database/search/#327bec45-5455-4633-a8b0-7c612751c478\n"
}

# ----- ENTRY POINT -----

FP_TEMP_DIR=""
if [ -e "/tmp/flashpoint-manager.lock" ]; then
    printf "Another instance of the Flashpoint manager is already running.\nPlease wait until it finishes.\nIf you are positive this script isn't running anywhere else you can run 'rm -f /tmp/flashpoint-manager.lock' to remove this error.\n"; exit 1
fi
trap 'rm "/tmp/flashpoint-manager.lock"' EXIT
touch "/tmp/flashpoint-manager.lock"

if [ -z "${1:-}" ]; then
    help_list_fun; exit 2
fi

case "$1" in
    --help)
        if [ $# -ne 1 ]; then
            printf "Error: --help does not accept extra arguments.\n"; exit 2
        fi
        help_list_fun; exit 0
        ;;
    --install-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --install-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            :
        else
            printf "Flashpoint is already installed.\n"; check_distrobox_fun; exit 2
        fi
        create_distrobox_fun
        file_extraction_fun
        finish_install_fun
        exit 0
        ;;
    --update-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --update-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        check_distrobox_fun
        file_extraction_fun
        update_fp_fun
        exit 0
        ;;
    --reinstall-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --reinstall-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        delete_fp_fun
        delete_distrobox_fun
        create_distrobox_fun
        file_extraction_fun
        finish_install_fun
        exit 0
        ;;
    --delete-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --delete-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        delete_distrobox_fun
        delete_fp_fun
        printf "Everything has been deleted except the Fedora 40 container image! You'll have to do that yourself with Docker or Podman.\n"
        exit 0
        ;;
    --enable-wine-wayland)
        if [ $# -ne 1 ]; then
            printf "Error: --enable-wine-wayland does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        check_distrobox_fun
        win_wy_on_fun
        exit 0
        ;;
    --disable-wine-wayland)
        if [ $# -ne 1 ]; then
            printf "Error: --disable-wine-wayland does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        check_distrobox_fun
        win_wy_off_fun
        exit 0
        ;;
    --enable-audio-fix)
        if [ $# -ne 1 ]; then
            printf "Error: --enable-audio-fix does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        check_distrobox_fun
        ad_fx_on_fun
        exit 0
        ;;
    --disable-audio-fix)
        if [ $# -ne 1 ]; then
            printf "Error: --disable-audio-fix does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        check_distrobox_fun
        ad_fx_off_fun
        exit 0
        ;;
    --easter-egg)
        if [ $# -ne 1 ]; then
            printf "Error: --easter-egg does not accept extra arguments.\n"; exit 2
        fi
        easter_egg_fun
        exit 0
        ;;
    --restore-distrobox)
        if [ $# -ne 1 ]; then
            printf "Error: --restore-distrobox does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        if ! check_install_fun; then
            printf "Flashpoint is not installed.\n"; exit 1
        fi
        delete_distrobox_fun
        create_distrobox_fun
        exit 0
        ;;
    *)
        printf "Unknown Command: \"$1\"\n"
        help_list_fun
        exit 2
        ;;
esac
