#!/bin/bash
set -uo pipefail

check_dependencies_fun() {
    command -v {podman,docker,lilipod} || {
        printf "A container engine must be installed.\n"; exit 1
    }
    command -v distrobox || {
        printf printf "Distrobox must be installed.\nhttps://distrobox.it/#installation\n"; exit 1
    }
}

create_distrobox_fun() {
    distrobox list | grep -q '\<Flashpoint\>' && {
        printf "The Distrobox container already exists. (Did you already have a Distrobox contained named 'Flashpoint'?\n"; exit 2
    }
    printf "Distrobox will install a Fedora 40 image with all the dependencies for Flashpoint. (This will take a while)\n"
    distrobox-create \
        --no-entry \
        --image fedora:40 \
        --home "$HOME/.flashpoint/" \
        --name Flashpoint \
        --additional-packages "
            xorg-x11-server-Xwayland
            gtk3
            nss
            pipewire-pulseaudio
            php
            p7zip
            wine
            libXcomposite.i686
            pulseaudio-libs.i686
            gtk2
            libXt" \
        --nvidia \
        --yes || {
            printf "Failed to create the Distrobox container.\n"; exit 2
        }
}

delete_distrobox_fun() {
    distrobox-rm Flashpoint --force --yes
}

delete_fp_fun() {
    rm -rf "$HOME/.flashpoint"
    rm -f "$HOME/.local/bin/flashpointwrapper.sh"
    rm -f "$HOME/.local/share/applications/flashpoint-archive.desktop"
}

# This function updates (or downgrades) Flashpoint and tries it's best to preserve data.
# The update proccess kinda sucks because it is complicated, but whatever it works and IMO it is the best way of updating.
# The update works by taking a new .7z Flashpoint file and cross checking the "version.txt" file inside it with the currently installed one.
# This allows for downgrades also but this isn't made for that.
# If an update is needed then the simple way of explaining it is the user data from their current install is copied to a temporary directory.
# Then the users whole Flashpoint install gets deleted and replaced with the new version that was extracted.
# After that the user data gets put back where it needs to be and some clean ups happen thats it.
update_fp_fun() {
    local YN USERDATA

    [ "$(< "$FP_TEMP_DIR/version.txt")" = "$(< "$HOME/.flashpoint/fp-dt/version.txt")" ] && {
        printf "Flashpoint is already up-to-date.\n"; rm -rf "$FP_TEMP_DIR"; exit 0
    }

    printf "Flashpoint is outdated! Would you like to update?\n"
    read -rp "[Y/n] " YN; YN="${YN:-Y}"
    if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
        printf "Starting update..\n"
    elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
        printf "Canceling update.\n"; rm -rf "$FP_TEMP_DIR"; exit 0
    else
        printf "Unknown option, exiting..\n"; rm -rf "$FP_TEMP_DIR"; exit 2
    fi

    # Save user data.
    USERDATA="$(mktemp -d "$HOME/.flashpoint/userdata.XXXXXX")"
    cp "$HOME/.flashpoint/fp-dt/preferences.json" "$USERDATA"
    cp "$HOME/.flashpoint/fp-dt/Data/Playlists/Favorites.json" "$USERDATA"
    cp "$HOME/.flashpoint/fp-dt/Data/flashpoint.sqlite" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/Data/Games" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/Legacy/htdocs" "$USERDATA"
    cp -r "$HOME/.flashpoint/fp-dt/FPSoftware/Wine" "$USERDATA"

    # Remove fp-dt and replace with the new version.
    rm -rf "$HOME/.flashpoint/fp-dt/";mv "$FP_TEMP_DIR" "$HOME/.flashpoint/fp-dt"

    # Remove conflicting data.
    rm -f "$HOME/.flashpoint/fp-dt/preferences.json"
    rm -f "$HOME/.flashpoint/fp-dt/Data/Playlists/Favorites.json"
    rm -f "$HOME/.flashpoint/fp-dt/Data/flashpoint.sqlite"
    rm -rf "$HOME/.flashpoint/fp-dt/Data/Games"
    rm -rf "$HOME/.flashpoint/fp-dt/Legacy/htdocs"

    # Restore user data.
    cp "$USERDATA/preferences.json" "$HOME/.flashpoint/fp-dt"
    cp "$USERDATA/Favorites.json" "$HOME/.flashpoint/fp-dt/Data/Playlists/"
    cp "$USERDATA/flashpoint.sqlite" "$HOME/.flashpoint/fp-dt/Data/"
    cp -r "$USERDATA/Games" "$HOME/.flashpoint/fp-dt/Data/"
    cp -r "$USERDATA/htdocs" "$HOME/.flashpoint/fp-dt/Legacy/"
    cp -r "$USERDATA/Wine" "$HOME/.flashpoint/fp-dt/FPSoftware/"

    # Remove extra user data directory.
    rm -rf "$USERDATA"; printf "Flashpoint has been updated.\n"
}

finish_install_fun() {
    mv "$FP_TEMP_DIR" "$HOME/.flashpoint/fp-dt"
    distrobox-enter Flashpoint --no-tty -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wineboot'
    distrobox-stop Flashpoint --yes

    mkdir -p "$HOME/.local/bin"
    cat > "$HOME/.local/bin/flashpointwrapper.sh" <<EOF
#!/bin/bash
trap "distrobox-stop Flashpoint --yes" EXIT
distrobox-enter Flashpoint -T -- bash -c '/usr/bin/env -S WINEPREFIX="$HOME/.flashpoint/fp-dt/FPSoftware/Wine" "$HOME/.flashpoint/fp-dt/Launcher/flashpoint-launcher" --js-flags=--lite_mode --ozone-platform-hint=auto'
EOF
    cat > "$HOME/.local/share/applications/flashpoint-archive.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Flashpoint Archive
Comment=An archive for games and animations from the web.
Icon=$HOME/.flashpoint/fp-dt/Launcher/icon.svg
StartupWMClass=flashpoint-launcher
Exec=$HOME/.local/bin/flashpointwrapper.sh
Path=$HOME/.flashpoint/fp-dt/Launcher
Terminal=false
Categories=Archiving;Game;
SingleMainWindow=true
EOF
    chmod +x "$HOME/.local/bin/flashpointwrapper.sh"; printf "Flashpoint has been installed.\n"
}

file_extraction_fun() {
    local FILEPATH

    FP_TEMP_DIR="$(mktemp -d "$HOME/.flashpoint/flashpoint.XXXXXX")"
    read -e -p "Enter the location of the Flashpoint .7z file: " FILEPATH; FILEPATH="${FILEPATH/#\~/$HOME}"

    [ ! -f "$FILEPATH" ] && {
        printf "File does not exist\n"; exit 2
    }
    [[ "$FILEPATH" != *.7z ]] && {
        printf "The file must be a .7z archive\n"; exit 2
    }

    if distrobox-enter Flashpoint --not-tty -- bash -c '7z l "$1"' bash "$FILEPATH" | grep -q "version.txt"; then
        printf "Extracting the zip file..\n"
        distrobox-enter Flashpoint --not-tty -- bash -c '7za x "$1" -o"$2"' bash "$FILEPATH" "$FP_TEMP_DIR" || {
            printf "Extraction failed!\n"; distrobox-stop Flashpoint --yes; exit 1
        }
    else
        printf "The provided .7z archive wasn't Flashpoint.\n"; distrobox-stop Flashpoint --yes; exit 2
    fi

    distrobox-stop Flashpoint --yes
    rm -rf "$FP_TEMP_DIR/Libraries"; rm -rf "$FP_TEMP_DIR/FPSoftware/Wine"; mkdir -p "$FP_TEMP_DIR/FPSoftware/Wine"
}

check_install_fun() {
    grep -q "Flashpoint" "$HOME/.flashpoint/fp-dt/version.txt"
}

ad_fx_on_fun() {
    local YN

    [ "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" = '"Audio"="alsa"' ] && {
        printf "Audio fix is already enabled.\n"; exit 2
    }

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Audio /d alsa /f' || {
        printf "Failed to enabled audio fix.\n"; exit 1
    }
    distrobox-stop Flashpoint --yes; printf "Audio fix enabled.\n"
}

ad_fx_off_fun() {
    local YN

    [ "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" = '"Audio"="pulse"' ] || [ -z "$(grep '"Audio"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" ] && {
        printf "Audio fix is already disabled\n"; exit 2
    }

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Audio /d pulse /f' || {
        printf "Failed to disable audio fix.\n"; exit 1
    }
    distrobox-stop Flashpoint --yes; printf "Audio fix disabled.\n"
}

win_wy_off_fun() {
    local YN

    [ "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" = '"Graphics"="x11,wayland"' ] || [ -z "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" ] && {
        printf "X11 is already in use.\n"; exit 2
    }

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN; YN="${YN:-Y}"
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Graphics /d x11,wayland /f'; {
        printf "Failed to disable WINE Wayland.\n"; exit 1
    }
    distrobox-stop Flashpoint --yes; printf "Wine Wayland disabled.\n"
}

win_wy_on_fun() {
    local YN

    [ "$(grep '"Graphics"' "$HOME/.flashpoint/fp-dt/FPSoftware/Wine/user.reg")" = '"Graphics"="wayland,x11"' ] || {
        printf "Wine native Wayland already in use.\n"; exit 2
    }

    if pgrep -f "flashpoint-archive"; then
        printf "To change Wine settings Flashpoint must be closed! Would you like to close it now?\n"
        read -rp "[Y/n] " YN
        if [[ "$YN" =~ ^([Yy]|[Yy][Ee][Ss])$ ]]; then
            pkill -SIGTERM -f flashpoint-archive; sleep 5
        elif [[ "$YN" =~ ^([Nn]|[Nn][Oo])$ ]]; then
            printf "Ok we won't close Flashpoint.\n"; exit 0
        else
            printf "Unknown option, exiting..\n"; exit 2
        fi
    fi

    distrobox-enter Flashpoint -T -- bash -c 'WINEPREFIX="$HOME/fp-dt/FPSoftware/Wine" wine reg add "HKCU\Software\Wine\Drivers" /v Graphics /d wayland,x11 /f' || {
        printf "Failed to enable WINE Wayland.\n"; exit 1
    }
    distrobox-stop Flashpoint --yes; printf "Wine Wayland enabled.\n"
}

help_list_fun() { # Help list.
    cat <<EOF
Usage:
--help                 |  Brings up the manager options.
--install-flashpoint   |  Installs Flashpoint and the Distrobox container.
--update-flashpoint    |  Updates Flashpoint.
--reinstall-flashpoint |  Re-installs Flashpoint and the Distrobox container.
--delete-flashpoint    |  Deletes Flashpoint the Distrobox container.
--enable-wine-wayland  |  Enables Wine native Wayland. (Disabled by default)
--disable-wine-wayland |  Disables Wine native Wayland. (Disabled by default)
--enable-audio-fix     |  Enables ALSA audio backend for Wine this can fix issue with audio. (Disabled by default)
--disable-audio-fix    |  Disables the ALSA audio backend in favor of PulseAudio. (Disabled by default)
--restore-container    |  Restores Distrobox container if it was deleted. (User data will be safe)
EOF
}

easter_egg_fun() {
    printf "You found the easter egg! :)\nThis is my favorite game on Flashpoint.\nhttps://flashpointproject.github.io/flashpoint-database/search/#327bec45-5455-4633-a8b0-7c612751c478\n"
}

##### entry point #####
FP_TEMP_DIR=""

if [ -e "/tmp/flashpoint-manager.lock" ]; then
    printf "Another instance of the Flashpoint manager is already running.\nPlease wait until it finishes.\nIf you are positive this script isn't running anywhere else you can run 'rm -f /tmp/flashpoint-manager.lock' to remove this error.\n"; exit 1
fi
trap 'rm -f "/tmp/flashpoint-manager.lock"' EXIT
touch "/tmp/flashpoint-manager.lock"

if [ -z "${1:-}" ]; then
    help_list_fun; exit 2
fi

case "$1" in
    --help)
        if [ $# -ne 1 ]; then
            printf "Error: --help does not accept extra arguments.\n"; exit 2
        fi
        help_list_fun; exit 0
        ;;
    --install-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --install-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        create_distrobox_fun
        file_extraction_fun
        finish_install_fun
        exit 0
        ;;
    --update-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --update-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        file_extraction_fun
        update_fp_fun
        exit 0
        ;;
    --reinstall-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --reinstall-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        delete_fp_fun
        delete_distrobox_fun
        check_distrobox_fun
        create_distrobox_fun
        file_extraction_fun
        finish_install_fun
        exit 0
        ;;
    --delete-flashpoint)
        if [ $# -ne 1 ]; then
            printf "Error: --delete-flashpoint does not accept extra arguments.\n"; exit 2
        fi
        check_install_fun
        delete_distrobox_fun
        delete_fp_fun
        printf "Everything has been deleted except the Fedora 40 container image! You'll have to do that yourself with Docker or Podman.\n"
        exit 0
        ;;
    --enable-wine-wayland)
        if [ $# -ne 1 ]; then
            printf "Error: --enable-wine-wayland does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        win_wy_on_fun
        exit 0
        ;;
    --disable-wine-wayland)
        if [ $# -ne 1 ]; then
            printf "Error: --disable-wine-wayland does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        win_wy_off_fun
        exit 0
        ;;
    --enable-audio-fix)
        if [ $# -ne 1 ]; then
            printf "Error: --enable-audio-fix does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        ad_fx_on_fun
        exit 0
        ;;
    --disable-audio-fix)
        if [ $# -ne 1 ]; then
            printf "Error: --disable-audio-fix does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        ad_fx_off_fun
        exit 0
        ;;
    --easter-egg)
        if [ $# -ne 1 ]; then
            printf "Error: --easter-egg does not accept extra arguments.\n"; exit 2
        fi
        easter_egg_fun
        exit 0
        ;;
    --restore-container)
        if [ $# -ne 1 ]; then
            printf "Error: --restore-container does not accept extra arguments.\n"; exit 2
        fi
        check_dependencies_fun
        check_install_fun
        check_distrobox_fun
        create_distrobox_fun
        exit 0
        ;;
    *)
        printf "Unknown Command: \"$1\"\n"
        help_list_fun
        exit 2
        ;;
esac
